import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import Provider from './provider'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: 'Mini project | atuandev',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Provider>
      <html lang='en'>
        <body
          className={cn(
            'font-sans antialiased',
            fontSans.variable
          )}
        >
          {children}
        </body>
      </html>
    </Provider>
  )
}
